// Generated by Molecule 0.8.0
#![allow(
    clippy::needless_lifetimes,
    clippy::needless_borrow,
    clippy::derivable_impls,
    clippy::clone_on_copy,
    clippy::write_literal,
    clippy::if_same_then_else,
    clippy::useless_conversion,
    clippy::redundant_slicing
)]

use super::blockchain::*;
use molecule::prelude::*;
#[derive(Clone)]
pub struct Uint128Opt(molecule::bytes::Bytes);
impl ::core::fmt::LowerHex for Uint128Opt {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        use molecule::hex_string;
        if f.alternate() {
            write!(f, "0x")?;
        }
        write!(f, "{}", hex_string(self.as_slice()))
    }
}
impl ::core::fmt::Debug for Uint128Opt {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{}({:#x})", Self::NAME, self)
    }
}
impl ::core::fmt::Display for Uint128Opt {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        if let Some(v) = self.to_opt() {
            write!(f, "{}(Some({}))", Self::NAME, v)
        } else {
            write!(f, "{}(None)", Self::NAME)
        }
    }
}
impl ::core::default::Default for Uint128Opt {
    fn default() -> Self {
        let v = molecule::bytes::Bytes::from_static(&Self::DEFAULT_VALUE);
        Uint128Opt::new_unchecked(v)
    }
}
impl Uint128Opt {
    const DEFAULT_VALUE: [u8; 0] = [];
    pub fn is_none(&self) -> bool {
        self.0.is_empty()
    }
    pub fn is_some(&self) -> bool {
        !self.0.is_empty()
    }
    pub fn to_opt(&self) -> Option<Uint128> {
        if self.is_none() {
            None
        } else {
            Some(Uint128::new_unchecked(self.0.clone()))
        }
    }
    pub fn as_reader<'r>(&'r self) -> Uint128OptReader<'r> {
        Uint128OptReader::new_unchecked(self.as_slice())
    }
}
impl molecule::prelude::Entity for Uint128Opt {
    type Builder = Uint128OptBuilder;
    const NAME: &'static str = "Uint128Opt";
    fn new_unchecked(data: molecule::bytes::Bytes) -> Self {
        Uint128Opt(data)
    }
    fn as_bytes(&self) -> molecule::bytes::Bytes {
        self.0.clone()
    }
    fn as_slice(&self) -> &[u8] {
        &self.0[..]
    }
    fn from_slice(slice: &[u8]) -> molecule::error::VerificationResult<Self> {
        Uint128OptReader::from_slice(slice).map(|reader| reader.to_entity())
    }
    fn from_compatible_slice(slice: &[u8]) -> molecule::error::VerificationResult<Self> {
        Uint128OptReader::from_compatible_slice(slice).map(|reader| reader.to_entity())
    }
    fn new_builder() -> Self::Builder {
        ::core::default::Default::default()
    }
    fn as_builder(self) -> Self::Builder {
        Self::new_builder().set(self.to_opt())
    }
}
#[derive(Clone, Copy)]
pub struct Uint128OptReader<'r>(&'r [u8]);
impl<'r> ::core::fmt::LowerHex for Uint128OptReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        use molecule::hex_string;
        if f.alternate() {
            write!(f, "0x")?;
        }
        write!(f, "{}", hex_string(self.as_slice()))
    }
}
impl<'r> ::core::fmt::Debug for Uint128OptReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{}({:#x})", Self::NAME, self)
    }
}
impl<'r> ::core::fmt::Display for Uint128OptReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        if let Some(v) = self.to_opt() {
            write!(f, "{}(Some({}))", Self::NAME, v)
        } else {
            write!(f, "{}(None)", Self::NAME)
        }
    }
}
impl<'r> Uint128OptReader<'r> {
    pub fn is_none(&self) -> bool {
        self.0.is_empty()
    }
    pub fn is_some(&self) -> bool {
        !self.0.is_empty()
    }
    pub fn to_opt(&self) -> Option<Uint128Reader<'r>> {
        if self.is_none() {
            None
        } else {
            Some(Uint128Reader::new_unchecked(self.as_slice()))
        }
    }
}
impl<'r> molecule::prelude::Reader<'r> for Uint128OptReader<'r> {
    type Entity = Uint128Opt;
    const NAME: &'static str = "Uint128OptReader";
    fn to_entity(&self) -> Self::Entity {
        Self::Entity::new_unchecked(self.as_slice().to_owned().into())
    }
    fn new_unchecked(slice: &'r [u8]) -> Self {
        Uint128OptReader(slice)
    }
    fn as_slice(&self) -> &'r [u8] {
        self.0
    }
    fn verify(slice: &[u8], compatible: bool) -> molecule::error::VerificationResult<()> {
        if !slice.is_empty() {
            Uint128Reader::verify(&slice[..], compatible)?;
        }
        Ok(())
    }
}
#[derive(Clone, Debug, Default)]
pub struct Uint128OptBuilder(pub(crate) Option<Uint128>);
impl Uint128OptBuilder {
    pub fn set(mut self, v: Option<Uint128>) -> Self {
        self.0 = v;
        self
    }
}
impl molecule::prelude::Builder for Uint128OptBuilder {
    type Entity = Uint128Opt;
    const NAME: &'static str = "Uint128OptBuilder";
    fn expected_length(&self) -> usize {
        self.0
            .as_ref()
            .map(|ref inner| inner.as_slice().len())
            .unwrap_or(0)
    }
    fn write<W: molecule::io::Write>(&self, writer: &mut W) -> molecule::io::Result<()> {
        self.0
            .as_ref()
            .map(|ref inner| writer.write_all(inner.as_slice()))
            .unwrap_or(Ok(()))
    }
    fn build(&self) -> Self::Entity {
        let mut inner = Vec::with_capacity(self.expected_length());
        self.write(&mut inner)
            .unwrap_or_else(|_| panic!("{} build should be ok", Self::NAME));
        Uint128Opt::new_unchecked(inner.into())
    }
}
impl From<Uint128> for Uint128Opt {
    fn from(value: Uint128) -> Self {
        Self::new_builder().set(Some(value)).build()
    }
}
#[derive(Clone)]
pub struct BuyIntentData(molecule::bytes::Bytes);
impl ::core::fmt::LowerHex for BuyIntentData {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        use molecule::hex_string;
        if f.alternate() {
            write!(f, "0x")?;
        }
        write!(f, "{}", hex_string(self.as_slice()))
    }
}
impl ::core::fmt::Debug for BuyIntentData {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{}({:#x})", Self::NAME, self)
    }
}
impl ::core::fmt::Display for BuyIntentData {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{} {{ ", Self::NAME)?;
        write!(
            f,
            "{}: {}",
            "dob_selling_script_hash",
            self.dob_selling_script_hash()
        )?;
        write!(f, ", {}: {}", "xudt_script_hash", self.xudt_script_hash())?;
        write!(f, ", {}: {}", "price", self.price())?;
        write!(f, ", {}: {}", "min_capacity", self.min_capacity())?;
        write!(f, ", {}: {}", "expire_since", self.expire_since())?;
        write!(f, ", {}: {}", "owner_script_hash", self.owner_script_hash())?;
        write!(f, " }}")
    }
}
impl ::core::default::Default for BuyIntentData {
    fn default() -> Self {
        let v = molecule::bytes::Bytes::from_static(&Self::DEFAULT_VALUE);
        BuyIntentData::new_unchecked(v)
    }
}
impl BuyIntentData {
    const DEFAULT_VALUE: [u8; 128] = [
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
    ];
    pub const TOTAL_SIZE: usize = 128;
    pub const FIELD_SIZES: [usize; 6] = [32, 32, 16, 8, 8, 32];
    pub const FIELD_COUNT: usize = 6;
    pub fn dob_selling_script_hash(&self) -> Byte32 {
        Byte32::new_unchecked(self.0.slice(0..32))
    }
    pub fn xudt_script_hash(&self) -> Byte32 {
        Byte32::new_unchecked(self.0.slice(32..64))
    }
    pub fn price(&self) -> Uint128 {
        Uint128::new_unchecked(self.0.slice(64..80))
    }
    pub fn min_capacity(&self) -> Uint64 {
        Uint64::new_unchecked(self.0.slice(80..88))
    }
    pub fn expire_since(&self) -> Uint64 {
        Uint64::new_unchecked(self.0.slice(88..96))
    }
    pub fn owner_script_hash(&self) -> Byte32 {
        Byte32::new_unchecked(self.0.slice(96..128))
    }
    pub fn as_reader<'r>(&'r self) -> BuyIntentDataReader<'r> {
        BuyIntentDataReader::new_unchecked(self.as_slice())
    }
}
impl molecule::prelude::Entity for BuyIntentData {
    type Builder = BuyIntentDataBuilder;
    const NAME: &'static str = "BuyIntentData";
    fn new_unchecked(data: molecule::bytes::Bytes) -> Self {
        BuyIntentData(data)
    }
    fn as_bytes(&self) -> molecule::bytes::Bytes {
        self.0.clone()
    }
    fn as_slice(&self) -> &[u8] {
        &self.0[..]
    }
    fn from_slice(slice: &[u8]) -> molecule::error::VerificationResult<Self> {
        BuyIntentDataReader::from_slice(slice).map(|reader| reader.to_entity())
    }
    fn from_compatible_slice(slice: &[u8]) -> molecule::error::VerificationResult<Self> {
        BuyIntentDataReader::from_compatible_slice(slice).map(|reader| reader.to_entity())
    }
    fn new_builder() -> Self::Builder {
        ::core::default::Default::default()
    }
    fn as_builder(self) -> Self::Builder {
        Self::new_builder()
            .dob_selling_script_hash(self.dob_selling_script_hash())
            .xudt_script_hash(self.xudt_script_hash())
            .price(self.price())
            .min_capacity(self.min_capacity())
            .expire_since(self.expire_since())
            .owner_script_hash(self.owner_script_hash())
    }
}
#[derive(Clone, Copy)]
pub struct BuyIntentDataReader<'r>(&'r [u8]);
impl<'r> ::core::fmt::LowerHex for BuyIntentDataReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        use molecule::hex_string;
        if f.alternate() {
            write!(f, "0x")?;
        }
        write!(f, "{}", hex_string(self.as_slice()))
    }
}
impl<'r> ::core::fmt::Debug for BuyIntentDataReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{}({:#x})", Self::NAME, self)
    }
}
impl<'r> ::core::fmt::Display for BuyIntentDataReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{} {{ ", Self::NAME)?;
        write!(
            f,
            "{}: {}",
            "dob_selling_script_hash",
            self.dob_selling_script_hash()
        )?;
        write!(f, ", {}: {}", "xudt_script_hash", self.xudt_script_hash())?;
        write!(f, ", {}: {}", "price", self.price())?;
        write!(f, ", {}: {}", "min_capacity", self.min_capacity())?;
        write!(f, ", {}: {}", "expire_since", self.expire_since())?;
        write!(f, ", {}: {}", "owner_script_hash", self.owner_script_hash())?;
        write!(f, " }}")
    }
}
impl<'r> BuyIntentDataReader<'r> {
    pub const TOTAL_SIZE: usize = 128;
    pub const FIELD_SIZES: [usize; 6] = [32, 32, 16, 8, 8, 32];
    pub const FIELD_COUNT: usize = 6;
    pub fn dob_selling_script_hash(&self) -> Byte32Reader<'r> {
        Byte32Reader::new_unchecked(&self.as_slice()[0..32])
    }
    pub fn xudt_script_hash(&self) -> Byte32Reader<'r> {
        Byte32Reader::new_unchecked(&self.as_slice()[32..64])
    }
    pub fn price(&self) -> Uint128Reader<'r> {
        Uint128Reader::new_unchecked(&self.as_slice()[64..80])
    }
    pub fn min_capacity(&self) -> Uint64Reader<'r> {
        Uint64Reader::new_unchecked(&self.as_slice()[80..88])
    }
    pub fn expire_since(&self) -> Uint64Reader<'r> {
        Uint64Reader::new_unchecked(&self.as_slice()[88..96])
    }
    pub fn owner_script_hash(&self) -> Byte32Reader<'r> {
        Byte32Reader::new_unchecked(&self.as_slice()[96..128])
    }
}
impl<'r> molecule::prelude::Reader<'r> for BuyIntentDataReader<'r> {
    type Entity = BuyIntentData;
    const NAME: &'static str = "BuyIntentDataReader";
    fn to_entity(&self) -> Self::Entity {
        Self::Entity::new_unchecked(self.as_slice().to_owned().into())
    }
    fn new_unchecked(slice: &'r [u8]) -> Self {
        BuyIntentDataReader(slice)
    }
    fn as_slice(&self) -> &'r [u8] {
        self.0
    }
    fn verify(slice: &[u8], _compatible: bool) -> molecule::error::VerificationResult<()> {
        use molecule::verification_error as ve;
        let slice_len = slice.len();
        if slice_len != Self::TOTAL_SIZE {
            return ve!(Self, TotalSizeNotMatch, Self::TOTAL_SIZE, slice_len);
        }
        Ok(())
    }
}
#[derive(Clone, Debug, Default)]
pub struct BuyIntentDataBuilder {
    pub(crate) dob_selling_script_hash: Byte32,
    pub(crate) xudt_script_hash: Byte32,
    pub(crate) price: Uint128,
    pub(crate) min_capacity: Uint64,
    pub(crate) expire_since: Uint64,
    pub(crate) owner_script_hash: Byte32,
}
impl BuyIntentDataBuilder {
    pub const TOTAL_SIZE: usize = 128;
    pub const FIELD_SIZES: [usize; 6] = [32, 32, 16, 8, 8, 32];
    pub const FIELD_COUNT: usize = 6;
    pub fn dob_selling_script_hash(mut self, v: Byte32) -> Self {
        self.dob_selling_script_hash = v;
        self
    }
    pub fn xudt_script_hash(mut self, v: Byte32) -> Self {
        self.xudt_script_hash = v;
        self
    }
    pub fn price(mut self, v: Uint128) -> Self {
        self.price = v;
        self
    }
    pub fn min_capacity(mut self, v: Uint64) -> Self {
        self.min_capacity = v;
        self
    }
    pub fn expire_since(mut self, v: Uint64) -> Self {
        self.expire_since = v;
        self
    }
    pub fn owner_script_hash(mut self, v: Byte32) -> Self {
        self.owner_script_hash = v;
        self
    }
}
impl molecule::prelude::Builder for BuyIntentDataBuilder {
    type Entity = BuyIntentData;
    const NAME: &'static str = "BuyIntentDataBuilder";
    fn expected_length(&self) -> usize {
        Self::TOTAL_SIZE
    }
    fn write<W: molecule::io::Write>(&self, writer: &mut W) -> molecule::io::Result<()> {
        writer.write_all(self.dob_selling_script_hash.as_slice())?;
        writer.write_all(self.xudt_script_hash.as_slice())?;
        writer.write_all(self.price.as_slice())?;
        writer.write_all(self.min_capacity.as_slice())?;
        writer.write_all(self.expire_since.as_slice())?;
        writer.write_all(self.owner_script_hash.as_slice())?;
        Ok(())
    }
    fn build(&self) -> Self::Entity {
        let mut inner = Vec::with_capacity(self.expected_length());
        self.write(&mut inner)
            .unwrap_or_else(|_| panic!("{} build should be ok", Self::NAME));
        BuyIntentData::new_unchecked(inner.into())
    }
}
#[derive(Clone)]
pub struct DobSellingData(molecule::bytes::Bytes);
impl ::core::fmt::LowerHex for DobSellingData {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        use molecule::hex_string;
        if f.alternate() {
            write!(f, "0x")?;
        }
        write!(f, "{}", hex_string(self.as_slice()))
    }
}
impl ::core::fmt::Debug for DobSellingData {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{}({:#x})", Self::NAME, self)
    }
}
impl ::core::fmt::Display for DobSellingData {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{} {{ ", Self::NAME)?;
        write!(
            f,
            "{}: {}",
            "account_book_script_hash",
            self.account_book_script_hash()
        )?;
        write!(f, ", {}: {}", "spore_code_hash", self.spore_code_hash())?;
        write!(f, ", {}: {}", "spore_data_hash", self.spore_data_hash())?;
        write!(
            f,
            ", {}: {}",
            "buy_intent_code_hash",
            self.buy_intent_code_hash()
        )?;
        write!(f, ", {}: {}", "owner_script_hash", self.owner_script_hash())?;
        write!(f, " }}")
    }
}
impl ::core::default::Default for DobSellingData {
    fn default() -> Self {
        let v = molecule::bytes::Bytes::from_static(&Self::DEFAULT_VALUE);
        DobSellingData::new_unchecked(v)
    }
}
impl DobSellingData {
    const DEFAULT_VALUE: [u8; 160] = [
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    ];
    pub const TOTAL_SIZE: usize = 160;
    pub const FIELD_SIZES: [usize; 5] = [32, 32, 32, 32, 32];
    pub const FIELD_COUNT: usize = 5;
    pub fn account_book_script_hash(&self) -> Byte32 {
        Byte32::new_unchecked(self.0.slice(0..32))
    }
    pub fn spore_code_hash(&self) -> Byte32 {
        Byte32::new_unchecked(self.0.slice(32..64))
    }
    pub fn spore_data_hash(&self) -> Byte32 {
        Byte32::new_unchecked(self.0.slice(64..96))
    }
    pub fn buy_intent_code_hash(&self) -> Byte32 {
        Byte32::new_unchecked(self.0.slice(96..128))
    }
    pub fn owner_script_hash(&self) -> Byte32 {
        Byte32::new_unchecked(self.0.slice(128..160))
    }
    pub fn as_reader<'r>(&'r self) -> DobSellingDataReader<'r> {
        DobSellingDataReader::new_unchecked(self.as_slice())
    }
}
impl molecule::prelude::Entity for DobSellingData {
    type Builder = DobSellingDataBuilder;
    const NAME: &'static str = "DobSellingData";
    fn new_unchecked(data: molecule::bytes::Bytes) -> Self {
        DobSellingData(data)
    }
    fn as_bytes(&self) -> molecule::bytes::Bytes {
        self.0.clone()
    }
    fn as_slice(&self) -> &[u8] {
        &self.0[..]
    }
    fn from_slice(slice: &[u8]) -> molecule::error::VerificationResult<Self> {
        DobSellingDataReader::from_slice(slice).map(|reader| reader.to_entity())
    }
    fn from_compatible_slice(slice: &[u8]) -> molecule::error::VerificationResult<Self> {
        DobSellingDataReader::from_compatible_slice(slice).map(|reader| reader.to_entity())
    }
    fn new_builder() -> Self::Builder {
        ::core::default::Default::default()
    }
    fn as_builder(self) -> Self::Builder {
        Self::new_builder()
            .account_book_script_hash(self.account_book_script_hash())
            .spore_code_hash(self.spore_code_hash())
            .spore_data_hash(self.spore_data_hash())
            .buy_intent_code_hash(self.buy_intent_code_hash())
            .owner_script_hash(self.owner_script_hash())
    }
}
#[derive(Clone, Copy)]
pub struct DobSellingDataReader<'r>(&'r [u8]);
impl<'r> ::core::fmt::LowerHex for DobSellingDataReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        use molecule::hex_string;
        if f.alternate() {
            write!(f, "0x")?;
        }
        write!(f, "{}", hex_string(self.as_slice()))
    }
}
impl<'r> ::core::fmt::Debug for DobSellingDataReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{}({:#x})", Self::NAME, self)
    }
}
impl<'r> ::core::fmt::Display for DobSellingDataReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{} {{ ", Self::NAME)?;
        write!(
            f,
            "{}: {}",
            "account_book_script_hash",
            self.account_book_script_hash()
        )?;
        write!(f, ", {}: {}", "spore_code_hash", self.spore_code_hash())?;
        write!(f, ", {}: {}", "spore_data_hash", self.spore_data_hash())?;
        write!(
            f,
            ", {}: {}",
            "buy_intent_code_hash",
            self.buy_intent_code_hash()
        )?;
        write!(f, ", {}: {}", "owner_script_hash", self.owner_script_hash())?;
        write!(f, " }}")
    }
}
impl<'r> DobSellingDataReader<'r> {
    pub const TOTAL_SIZE: usize = 160;
    pub const FIELD_SIZES: [usize; 5] = [32, 32, 32, 32, 32];
    pub const FIELD_COUNT: usize = 5;
    pub fn account_book_script_hash(&self) -> Byte32Reader<'r> {
        Byte32Reader::new_unchecked(&self.as_slice()[0..32])
    }
    pub fn spore_code_hash(&self) -> Byte32Reader<'r> {
        Byte32Reader::new_unchecked(&self.as_slice()[32..64])
    }
    pub fn spore_data_hash(&self) -> Byte32Reader<'r> {
        Byte32Reader::new_unchecked(&self.as_slice()[64..96])
    }
    pub fn buy_intent_code_hash(&self) -> Byte32Reader<'r> {
        Byte32Reader::new_unchecked(&self.as_slice()[96..128])
    }
    pub fn owner_script_hash(&self) -> Byte32Reader<'r> {
        Byte32Reader::new_unchecked(&self.as_slice()[128..160])
    }
}
impl<'r> molecule::prelude::Reader<'r> for DobSellingDataReader<'r> {
    type Entity = DobSellingData;
    const NAME: &'static str = "DobSellingDataReader";
    fn to_entity(&self) -> Self::Entity {
        Self::Entity::new_unchecked(self.as_slice().to_owned().into())
    }
    fn new_unchecked(slice: &'r [u8]) -> Self {
        DobSellingDataReader(slice)
    }
    fn as_slice(&self) -> &'r [u8] {
        self.0
    }
    fn verify(slice: &[u8], _compatible: bool) -> molecule::error::VerificationResult<()> {
        use molecule::verification_error as ve;
        let slice_len = slice.len();
        if slice_len != Self::TOTAL_SIZE {
            return ve!(Self, TotalSizeNotMatch, Self::TOTAL_SIZE, slice_len);
        }
        Ok(())
    }
}
#[derive(Clone, Debug, Default)]
pub struct DobSellingDataBuilder {
    pub(crate) account_book_script_hash: Byte32,
    pub(crate) spore_code_hash: Byte32,
    pub(crate) spore_data_hash: Byte32,
    pub(crate) buy_intent_code_hash: Byte32,
    pub(crate) owner_script_hash: Byte32,
}
impl DobSellingDataBuilder {
    pub const TOTAL_SIZE: usize = 160;
    pub const FIELD_SIZES: [usize; 5] = [32, 32, 32, 32, 32];
    pub const FIELD_COUNT: usize = 5;
    pub fn account_book_script_hash(mut self, v: Byte32) -> Self {
        self.account_book_script_hash = v;
        self
    }
    pub fn spore_code_hash(mut self, v: Byte32) -> Self {
        self.spore_code_hash = v;
        self
    }
    pub fn spore_data_hash(mut self, v: Byte32) -> Self {
        self.spore_data_hash = v;
        self
    }
    pub fn buy_intent_code_hash(mut self, v: Byte32) -> Self {
        self.buy_intent_code_hash = v;
        self
    }
    pub fn owner_script_hash(mut self, v: Byte32) -> Self {
        self.owner_script_hash = v;
        self
    }
}
impl molecule::prelude::Builder for DobSellingDataBuilder {
    type Entity = DobSellingData;
    const NAME: &'static str = "DobSellingDataBuilder";
    fn expected_length(&self) -> usize {
        Self::TOTAL_SIZE
    }
    fn write<W: molecule::io::Write>(&self, writer: &mut W) -> molecule::io::Result<()> {
        writer.write_all(self.account_book_script_hash.as_slice())?;
        writer.write_all(self.spore_code_hash.as_slice())?;
        writer.write_all(self.spore_data_hash.as_slice())?;
        writer.write_all(self.buy_intent_code_hash.as_slice())?;
        writer.write_all(self.owner_script_hash.as_slice())?;
        Ok(())
    }
    fn build(&self) -> Self::Entity {
        let mut inner = Vec::with_capacity(self.expected_length());
        self.write(&mut inner)
            .unwrap_or_else(|_| panic!("{} build should be ok", Self::NAME));
        DobSellingData::new_unchecked(inner.into())
    }
}
#[derive(Clone)]
pub struct WithdrawalSporeInfo(molecule::bytes::Bytes);
impl ::core::fmt::LowerHex for WithdrawalSporeInfo {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        use molecule::hex_string;
        if f.alternate() {
            write!(f, "0x")?;
        }
        write!(f, "{}", hex_string(self.as_slice()))
    }
}
impl ::core::fmt::Debug for WithdrawalSporeInfo {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{}({:#x})", Self::NAME, self)
    }
}
impl ::core::fmt::Display for WithdrawalSporeInfo {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{} {{ ", Self::NAME)?;
        write!(f, "{}: {}", "spore_code_hash", self.spore_code_hash())?;
        write!(f, ", {}: {}", "spore_level", self.spore_level())?;
        write!(f, ", {}: {}", "spore_id", self.spore_id())?;
        write!(f, ", {}: {}", "cluster_id", self.cluster_id())?;
        write!(f, " }}")
    }
}
impl ::core::default::Default for WithdrawalSporeInfo {
    fn default() -> Self {
        let v = molecule::bytes::Bytes::from_static(&Self::DEFAULT_VALUE);
        WithdrawalSporeInfo::new_unchecked(v)
    }
}
impl WithdrawalSporeInfo {
    const DEFAULT_VALUE: [u8; 97] = [
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0,
    ];
    pub const TOTAL_SIZE: usize = 97;
    pub const FIELD_SIZES: [usize; 4] = [32, 1, 32, 32];
    pub const FIELD_COUNT: usize = 4;
    pub fn spore_code_hash(&self) -> Byte32 {
        Byte32::new_unchecked(self.0.slice(0..32))
    }
    pub fn spore_level(&self) -> Byte {
        Byte::new_unchecked(self.0.slice(32..33))
    }
    pub fn spore_id(&self) -> Byte32 {
        Byte32::new_unchecked(self.0.slice(33..65))
    }
    pub fn cluster_id(&self) -> Byte32 {
        Byte32::new_unchecked(self.0.slice(65..97))
    }
    pub fn as_reader<'r>(&'r self) -> WithdrawalSporeInfoReader<'r> {
        WithdrawalSporeInfoReader::new_unchecked(self.as_slice())
    }
}
impl molecule::prelude::Entity for WithdrawalSporeInfo {
    type Builder = WithdrawalSporeInfoBuilder;
    const NAME: &'static str = "WithdrawalSporeInfo";
    fn new_unchecked(data: molecule::bytes::Bytes) -> Self {
        WithdrawalSporeInfo(data)
    }
    fn as_bytes(&self) -> molecule::bytes::Bytes {
        self.0.clone()
    }
    fn as_slice(&self) -> &[u8] {
        &self.0[..]
    }
    fn from_slice(slice: &[u8]) -> molecule::error::VerificationResult<Self> {
        WithdrawalSporeInfoReader::from_slice(slice).map(|reader| reader.to_entity())
    }
    fn from_compatible_slice(slice: &[u8]) -> molecule::error::VerificationResult<Self> {
        WithdrawalSporeInfoReader::from_compatible_slice(slice).map(|reader| reader.to_entity())
    }
    fn new_builder() -> Self::Builder {
        ::core::default::Default::default()
    }
    fn as_builder(self) -> Self::Builder {
        Self::new_builder()
            .spore_code_hash(self.spore_code_hash())
            .spore_level(self.spore_level())
            .spore_id(self.spore_id())
            .cluster_id(self.cluster_id())
    }
}
#[derive(Clone, Copy)]
pub struct WithdrawalSporeInfoReader<'r>(&'r [u8]);
impl<'r> ::core::fmt::LowerHex for WithdrawalSporeInfoReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        use molecule::hex_string;
        if f.alternate() {
            write!(f, "0x")?;
        }
        write!(f, "{}", hex_string(self.as_slice()))
    }
}
impl<'r> ::core::fmt::Debug for WithdrawalSporeInfoReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{}({:#x})", Self::NAME, self)
    }
}
impl<'r> ::core::fmt::Display for WithdrawalSporeInfoReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{} {{ ", Self::NAME)?;
        write!(f, "{}: {}", "spore_code_hash", self.spore_code_hash())?;
        write!(f, ", {}: {}", "spore_level", self.spore_level())?;
        write!(f, ", {}: {}", "spore_id", self.spore_id())?;
        write!(f, ", {}: {}", "cluster_id", self.cluster_id())?;
        write!(f, " }}")
    }
}
impl<'r> WithdrawalSporeInfoReader<'r> {
    pub const TOTAL_SIZE: usize = 97;
    pub const FIELD_SIZES: [usize; 4] = [32, 1, 32, 32];
    pub const FIELD_COUNT: usize = 4;
    pub fn spore_code_hash(&self) -> Byte32Reader<'r> {
        Byte32Reader::new_unchecked(&self.as_slice()[0..32])
    }
    pub fn spore_level(&self) -> ByteReader<'r> {
        ByteReader::new_unchecked(&self.as_slice()[32..33])
    }
    pub fn spore_id(&self) -> Byte32Reader<'r> {
        Byte32Reader::new_unchecked(&self.as_slice()[33..65])
    }
    pub fn cluster_id(&self) -> Byte32Reader<'r> {
        Byte32Reader::new_unchecked(&self.as_slice()[65..97])
    }
}
impl<'r> molecule::prelude::Reader<'r> for WithdrawalSporeInfoReader<'r> {
    type Entity = WithdrawalSporeInfo;
    const NAME: &'static str = "WithdrawalSporeInfoReader";
    fn to_entity(&self) -> Self::Entity {
        Self::Entity::new_unchecked(self.as_slice().to_owned().into())
    }
    fn new_unchecked(slice: &'r [u8]) -> Self {
        WithdrawalSporeInfoReader(slice)
    }
    fn as_slice(&self) -> &'r [u8] {
        self.0
    }
    fn verify(slice: &[u8], _compatible: bool) -> molecule::error::VerificationResult<()> {
        use molecule::verification_error as ve;
        let slice_len = slice.len();
        if slice_len != Self::TOTAL_SIZE {
            return ve!(Self, TotalSizeNotMatch, Self::TOTAL_SIZE, slice_len);
        }
        Ok(())
    }
}
#[derive(Clone, Debug, Default)]
pub struct WithdrawalSporeInfoBuilder {
    pub(crate) spore_code_hash: Byte32,
    pub(crate) spore_level: Byte,
    pub(crate) spore_id: Byte32,
    pub(crate) cluster_id: Byte32,
}
impl WithdrawalSporeInfoBuilder {
    pub const TOTAL_SIZE: usize = 97;
    pub const FIELD_SIZES: [usize; 4] = [32, 1, 32, 32];
    pub const FIELD_COUNT: usize = 4;
    pub fn spore_code_hash(mut self, v: Byte32) -> Self {
        self.spore_code_hash = v;
        self
    }
    pub fn spore_level(mut self, v: Byte) -> Self {
        self.spore_level = v;
        self
    }
    pub fn spore_id(mut self, v: Byte32) -> Self {
        self.spore_id = v;
        self
    }
    pub fn cluster_id(mut self, v: Byte32) -> Self {
        self.cluster_id = v;
        self
    }
}
impl molecule::prelude::Builder for WithdrawalSporeInfoBuilder {
    type Entity = WithdrawalSporeInfo;
    const NAME: &'static str = "WithdrawalSporeInfoBuilder";
    fn expected_length(&self) -> usize {
        Self::TOTAL_SIZE
    }
    fn write<W: molecule::io::Write>(&self, writer: &mut W) -> molecule::io::Result<()> {
        writer.write_all(self.spore_code_hash.as_slice())?;
        writer.write_all(self.spore_level.as_slice())?;
        writer.write_all(self.spore_id.as_slice())?;
        writer.write_all(self.cluster_id.as_slice())?;
        Ok(())
    }
    fn build(&self) -> Self::Entity {
        let mut inner = Vec::with_capacity(self.expected_length());
        self.write(&mut inner)
            .unwrap_or_else(|_| panic!("{} build should be ok", Self::NAME));
        WithdrawalSporeInfo::new_unchecked(inner.into())
    }
}
#[derive(Clone)]
pub struct WithdrawalBuyer(molecule::bytes::Bytes);
impl ::core::fmt::LowerHex for WithdrawalBuyer {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        use molecule::hex_string;
        if f.alternate() {
            write!(f, "0x")?;
        }
        write!(f, "{}", hex_string(self.as_slice()))
    }
}
impl ::core::fmt::Debug for WithdrawalBuyer {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{}({:#x})", Self::NAME, self)
    }
}
impl ::core::fmt::Display for WithdrawalBuyer {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{}(", Self::NAME)?;
        self.to_enum().display_inner(f)?;
        write!(f, ")")
    }
}
impl ::core::default::Default for WithdrawalBuyer {
    fn default() -> Self {
        let v = molecule::bytes::Bytes::from_static(&Self::DEFAULT_VALUE);
        WithdrawalBuyer::new_unchecked(v)
    }
}
impl WithdrawalBuyer {
    const DEFAULT_VALUE: [u8; 101] = [
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    ];
    pub const ITEMS_COUNT: usize = 2;
    pub fn item_id(&self) -> molecule::Number {
        molecule::unpack_number(self.as_slice())
    }
    pub fn to_enum(&self) -> WithdrawalBuyerUnion {
        let inner = self.0.slice(molecule::NUMBER_SIZE..);
        match self.item_id() {
            0 => WithdrawalSporeInfo::new_unchecked(inner).into(),
            1 => Byte32::new_unchecked(inner).into(),
            _ => panic!("{}: invalid data", Self::NAME),
        }
    }
    pub fn as_reader<'r>(&'r self) -> WithdrawalBuyerReader<'r> {
        WithdrawalBuyerReader::new_unchecked(self.as_slice())
    }
}
impl molecule::prelude::Entity for WithdrawalBuyer {
    type Builder = WithdrawalBuyerBuilder;
    const NAME: &'static str = "WithdrawalBuyer";
    fn new_unchecked(data: molecule::bytes::Bytes) -> Self {
        WithdrawalBuyer(data)
    }
    fn as_bytes(&self) -> molecule::bytes::Bytes {
        self.0.clone()
    }
    fn as_slice(&self) -> &[u8] {
        &self.0[..]
    }
    fn from_slice(slice: &[u8]) -> molecule::error::VerificationResult<Self> {
        WithdrawalBuyerReader::from_slice(slice).map(|reader| reader.to_entity())
    }
    fn from_compatible_slice(slice: &[u8]) -> molecule::error::VerificationResult<Self> {
        WithdrawalBuyerReader::from_compatible_slice(slice).map(|reader| reader.to_entity())
    }
    fn new_builder() -> Self::Builder {
        ::core::default::Default::default()
    }
    fn as_builder(self) -> Self::Builder {
        Self::new_builder().set(self.to_enum())
    }
}
#[derive(Clone, Copy)]
pub struct WithdrawalBuyerReader<'r>(&'r [u8]);
impl<'r> ::core::fmt::LowerHex for WithdrawalBuyerReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        use molecule::hex_string;
        if f.alternate() {
            write!(f, "0x")?;
        }
        write!(f, "{}", hex_string(self.as_slice()))
    }
}
impl<'r> ::core::fmt::Debug for WithdrawalBuyerReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{}({:#x})", Self::NAME, self)
    }
}
impl<'r> ::core::fmt::Display for WithdrawalBuyerReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{}(", Self::NAME)?;
        self.to_enum().display_inner(f)?;
        write!(f, ")")
    }
}
impl<'r> WithdrawalBuyerReader<'r> {
    pub const ITEMS_COUNT: usize = 2;
    pub fn item_id(&self) -> molecule::Number {
        molecule::unpack_number(self.as_slice())
    }
    pub fn to_enum(&self) -> WithdrawalBuyerUnionReader<'r> {
        let inner = &self.as_slice()[molecule::NUMBER_SIZE..];
        match self.item_id() {
            0 => WithdrawalSporeInfoReader::new_unchecked(inner).into(),
            1 => Byte32Reader::new_unchecked(inner).into(),
            _ => panic!("{}: invalid data", Self::NAME),
        }
    }
}
impl<'r> molecule::prelude::Reader<'r> for WithdrawalBuyerReader<'r> {
    type Entity = WithdrawalBuyer;
    const NAME: &'static str = "WithdrawalBuyerReader";
    fn to_entity(&self) -> Self::Entity {
        Self::Entity::new_unchecked(self.as_slice().to_owned().into())
    }
    fn new_unchecked(slice: &'r [u8]) -> Self {
        WithdrawalBuyerReader(slice)
    }
    fn as_slice(&self) -> &'r [u8] {
        self.0
    }
    fn verify(slice: &[u8], compatible: bool) -> molecule::error::VerificationResult<()> {
        use molecule::verification_error as ve;
        let slice_len = slice.len();
        if slice_len < molecule::NUMBER_SIZE {
            return ve!(Self, HeaderIsBroken, molecule::NUMBER_SIZE, slice_len);
        }
        let item_id = molecule::unpack_number(slice);
        let inner_slice = &slice[molecule::NUMBER_SIZE..];
        match item_id {
            0 => WithdrawalSporeInfoReader::verify(inner_slice, compatible),
            1 => Byte32Reader::verify(inner_slice, compatible),
            _ => ve!(Self, UnknownItem, Self::ITEMS_COUNT, item_id),
        }?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default)]
pub struct WithdrawalBuyerBuilder(pub(crate) WithdrawalBuyerUnion);
impl WithdrawalBuyerBuilder {
    pub const ITEMS_COUNT: usize = 2;
    pub fn set<I>(mut self, v: I) -> Self
    where
        I: ::core::convert::Into<WithdrawalBuyerUnion>,
    {
        self.0 = v.into();
        self
    }
}
impl molecule::prelude::Builder for WithdrawalBuyerBuilder {
    type Entity = WithdrawalBuyer;
    const NAME: &'static str = "WithdrawalBuyerBuilder";
    fn expected_length(&self) -> usize {
        molecule::NUMBER_SIZE + self.0.as_slice().len()
    }
    fn write<W: molecule::io::Write>(&self, writer: &mut W) -> molecule::io::Result<()> {
        writer.write_all(&molecule::pack_number(self.0.item_id()))?;
        writer.write_all(self.0.as_slice())
    }
    fn build(&self) -> Self::Entity {
        let mut inner = Vec::with_capacity(self.expected_length());
        self.write(&mut inner)
            .unwrap_or_else(|_| panic!("{} build should be ok", Self::NAME));
        WithdrawalBuyer::new_unchecked(inner.into())
    }
}
#[derive(Debug, Clone)]
pub enum WithdrawalBuyerUnion {
    WithdrawalSporeInfo(WithdrawalSporeInfo),
    Byte32(Byte32),
}
#[derive(Debug, Clone, Copy)]
pub enum WithdrawalBuyerUnionReader<'r> {
    WithdrawalSporeInfo(WithdrawalSporeInfoReader<'r>),
    Byte32(Byte32Reader<'r>),
}
impl ::core::default::Default for WithdrawalBuyerUnion {
    fn default() -> Self {
        WithdrawalBuyerUnion::WithdrawalSporeInfo(::core::default::Default::default())
    }
}
impl ::core::fmt::Display for WithdrawalBuyerUnion {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        match self {
            WithdrawalBuyerUnion::WithdrawalSporeInfo(ref item) => {
                write!(f, "{}::{}({})", Self::NAME, WithdrawalSporeInfo::NAME, item)
            }
            WithdrawalBuyerUnion::Byte32(ref item) => {
                write!(f, "{}::{}({})", Self::NAME, Byte32::NAME, item)
            }
        }
    }
}
impl<'r> ::core::fmt::Display for WithdrawalBuyerUnionReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        match self {
            WithdrawalBuyerUnionReader::WithdrawalSporeInfo(ref item) => {
                write!(f, "{}::{}({})", Self::NAME, WithdrawalSporeInfo::NAME, item)
            }
            WithdrawalBuyerUnionReader::Byte32(ref item) => {
                write!(f, "{}::{}({})", Self::NAME, Byte32::NAME, item)
            }
        }
    }
}
impl WithdrawalBuyerUnion {
    pub(crate) fn display_inner(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        match self {
            WithdrawalBuyerUnion::WithdrawalSporeInfo(ref item) => write!(f, "{}", item),
            WithdrawalBuyerUnion::Byte32(ref item) => write!(f, "{}", item),
        }
    }
}
impl<'r> WithdrawalBuyerUnionReader<'r> {
    pub(crate) fn display_inner(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        match self {
            WithdrawalBuyerUnionReader::WithdrawalSporeInfo(ref item) => write!(f, "{}", item),
            WithdrawalBuyerUnionReader::Byte32(ref item) => write!(f, "{}", item),
        }
    }
}
impl ::core::convert::From<WithdrawalSporeInfo> for WithdrawalBuyerUnion {
    fn from(item: WithdrawalSporeInfo) -> Self {
        WithdrawalBuyerUnion::WithdrawalSporeInfo(item)
    }
}
impl ::core::convert::From<Byte32> for WithdrawalBuyerUnion {
    fn from(item: Byte32) -> Self {
        WithdrawalBuyerUnion::Byte32(item)
    }
}
impl<'r> ::core::convert::From<WithdrawalSporeInfoReader<'r>> for WithdrawalBuyerUnionReader<'r> {
    fn from(item: WithdrawalSporeInfoReader<'r>) -> Self {
        WithdrawalBuyerUnionReader::WithdrawalSporeInfo(item)
    }
}
impl<'r> ::core::convert::From<Byte32Reader<'r>> for WithdrawalBuyerUnionReader<'r> {
    fn from(item: Byte32Reader<'r>) -> Self {
        WithdrawalBuyerUnionReader::Byte32(item)
    }
}
impl WithdrawalBuyerUnion {
    pub const NAME: &'static str = "WithdrawalBuyerUnion";
    pub fn as_bytes(&self) -> molecule::bytes::Bytes {
        match self {
            WithdrawalBuyerUnion::WithdrawalSporeInfo(item) => item.as_bytes(),
            WithdrawalBuyerUnion::Byte32(item) => item.as_bytes(),
        }
    }
    pub fn as_slice(&self) -> &[u8] {
        match self {
            WithdrawalBuyerUnion::WithdrawalSporeInfo(item) => item.as_slice(),
            WithdrawalBuyerUnion::Byte32(item) => item.as_slice(),
        }
    }
    pub fn item_id(&self) -> molecule::Number {
        match self {
            WithdrawalBuyerUnion::WithdrawalSporeInfo(_) => 0,
            WithdrawalBuyerUnion::Byte32(_) => 1,
        }
    }
    pub fn item_name(&self) -> &str {
        match self {
            WithdrawalBuyerUnion::WithdrawalSporeInfo(_) => "WithdrawalSporeInfo",
            WithdrawalBuyerUnion::Byte32(_) => "Byte32",
        }
    }
    pub fn as_reader<'r>(&'r self) -> WithdrawalBuyerUnionReader<'r> {
        match self {
            WithdrawalBuyerUnion::WithdrawalSporeInfo(item) => item.as_reader().into(),
            WithdrawalBuyerUnion::Byte32(item) => item.as_reader().into(),
        }
    }
}
impl<'r> WithdrawalBuyerUnionReader<'r> {
    pub const NAME: &'r str = "WithdrawalBuyerUnionReader";
    pub fn as_slice(&self) -> &'r [u8] {
        match self {
            WithdrawalBuyerUnionReader::WithdrawalSporeInfo(item) => item.as_slice(),
            WithdrawalBuyerUnionReader::Byte32(item) => item.as_slice(),
        }
    }
    pub fn item_id(&self) -> molecule::Number {
        match self {
            WithdrawalBuyerUnionReader::WithdrawalSporeInfo(_) => 0,
            WithdrawalBuyerUnionReader::Byte32(_) => 1,
        }
    }
    pub fn item_name(&self) -> &str {
        match self {
            WithdrawalBuyerUnionReader::WithdrawalSporeInfo(_) => "WithdrawalSporeInfo",
            WithdrawalBuyerUnionReader::Byte32(_) => "Byte32",
        }
    }
}
impl From<WithdrawalSporeInfo> for WithdrawalBuyer {
    fn from(value: WithdrawalSporeInfo) -> Self {
        Self::new_builder().set(value).build()
    }
}
impl From<Byte32> for WithdrawalBuyer {
    fn from(value: Byte32) -> Self {
        Self::new_builder().set(value).build()
    }
}
#[derive(Clone)]
pub struct WithdrawalIntentData(molecule::bytes::Bytes);
impl ::core::fmt::LowerHex for WithdrawalIntentData {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        use molecule::hex_string;
        if f.alternate() {
            write!(f, "0x")?;
        }
        write!(f, "{}", hex_string(self.as_slice()))
    }
}
impl ::core::fmt::Debug for WithdrawalIntentData {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{}({:#x})", Self::NAME, self)
    }
}
impl ::core::fmt::Display for WithdrawalIntentData {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{} {{ ", Self::NAME)?;
        write!(f, "{}: {}", "xudt_script_hash", self.xudt_script_hash())?;
        write!(
            f,
            ", {}: {}",
            "xudt_lock_script_hash",
            self.xudt_lock_script_hash()
        )?;
        write!(f, ", {}: {}", "buyer", self.buyer())?;
        write!(f, ", {}: {}", "expire_since", self.expire_since())?;
        write!(f, ", {}: {}", "owner_script_hash", self.owner_script_hash())?;
        let extra_count = self.count_extra_fields();
        if extra_count != 0 {
            write!(f, ", .. ({} fields)", extra_count)?;
        }
        write!(f, " }}")
    }
}
impl ::core::default::Default for WithdrawalIntentData {
    fn default() -> Self {
        let v = molecule::bytes::Bytes::from_static(&Self::DEFAULT_VALUE);
        WithdrawalIntentData::new_unchecked(v)
    }
}
impl WithdrawalIntentData {
    const DEFAULT_VALUE: [u8; 229] = [
        229, 0, 0, 0, 24, 0, 0, 0, 56, 0, 0, 0, 88, 0, 0, 0, 189, 0, 0, 0, 197, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    ];
    pub const FIELD_COUNT: usize = 5;
    pub fn total_size(&self) -> usize {
        molecule::unpack_number(self.as_slice()) as usize
    }
    pub fn field_count(&self) -> usize {
        if self.total_size() == molecule::NUMBER_SIZE {
            0
        } else {
            (molecule::unpack_number(&self.as_slice()[molecule::NUMBER_SIZE..]) as usize / 4) - 1
        }
    }
    pub fn count_extra_fields(&self) -> usize {
        self.field_count() - Self::FIELD_COUNT
    }
    pub fn has_extra_fields(&self) -> bool {
        Self::FIELD_COUNT != self.field_count()
    }
    pub fn xudt_script_hash(&self) -> Byte32 {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[4..]) as usize;
        let end = molecule::unpack_number(&slice[8..]) as usize;
        Byte32::new_unchecked(self.0.slice(start..end))
    }
    pub fn xudt_lock_script_hash(&self) -> Byte32 {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[8..]) as usize;
        let end = molecule::unpack_number(&slice[12..]) as usize;
        Byte32::new_unchecked(self.0.slice(start..end))
    }
    pub fn buyer(&self) -> WithdrawalBuyer {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[12..]) as usize;
        let end = molecule::unpack_number(&slice[16..]) as usize;
        WithdrawalBuyer::new_unchecked(self.0.slice(start..end))
    }
    pub fn expire_since(&self) -> Uint64 {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[16..]) as usize;
        let end = molecule::unpack_number(&slice[20..]) as usize;
        Uint64::new_unchecked(self.0.slice(start..end))
    }
    pub fn owner_script_hash(&self) -> Byte32 {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[20..]) as usize;
        if self.has_extra_fields() {
            let end = molecule::unpack_number(&slice[24..]) as usize;
            Byte32::new_unchecked(self.0.slice(start..end))
        } else {
            Byte32::new_unchecked(self.0.slice(start..))
        }
    }
    pub fn as_reader<'r>(&'r self) -> WithdrawalIntentDataReader<'r> {
        WithdrawalIntentDataReader::new_unchecked(self.as_slice())
    }
}
impl molecule::prelude::Entity for WithdrawalIntentData {
    type Builder = WithdrawalIntentDataBuilder;
    const NAME: &'static str = "WithdrawalIntentData";
    fn new_unchecked(data: molecule::bytes::Bytes) -> Self {
        WithdrawalIntentData(data)
    }
    fn as_bytes(&self) -> molecule::bytes::Bytes {
        self.0.clone()
    }
    fn as_slice(&self) -> &[u8] {
        &self.0[..]
    }
    fn from_slice(slice: &[u8]) -> molecule::error::VerificationResult<Self> {
        WithdrawalIntentDataReader::from_slice(slice).map(|reader| reader.to_entity())
    }
    fn from_compatible_slice(slice: &[u8]) -> molecule::error::VerificationResult<Self> {
        WithdrawalIntentDataReader::from_compatible_slice(slice).map(|reader| reader.to_entity())
    }
    fn new_builder() -> Self::Builder {
        ::core::default::Default::default()
    }
    fn as_builder(self) -> Self::Builder {
        Self::new_builder()
            .xudt_script_hash(self.xudt_script_hash())
            .xudt_lock_script_hash(self.xudt_lock_script_hash())
            .buyer(self.buyer())
            .expire_since(self.expire_since())
            .owner_script_hash(self.owner_script_hash())
    }
}
#[derive(Clone, Copy)]
pub struct WithdrawalIntentDataReader<'r>(&'r [u8]);
impl<'r> ::core::fmt::LowerHex for WithdrawalIntentDataReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        use molecule::hex_string;
        if f.alternate() {
            write!(f, "0x")?;
        }
        write!(f, "{}", hex_string(self.as_slice()))
    }
}
impl<'r> ::core::fmt::Debug for WithdrawalIntentDataReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{}({:#x})", Self::NAME, self)
    }
}
impl<'r> ::core::fmt::Display for WithdrawalIntentDataReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{} {{ ", Self::NAME)?;
        write!(f, "{}: {}", "xudt_script_hash", self.xudt_script_hash())?;
        write!(
            f,
            ", {}: {}",
            "xudt_lock_script_hash",
            self.xudt_lock_script_hash()
        )?;
        write!(f, ", {}: {}", "buyer", self.buyer())?;
        write!(f, ", {}: {}", "expire_since", self.expire_since())?;
        write!(f, ", {}: {}", "owner_script_hash", self.owner_script_hash())?;
        let extra_count = self.count_extra_fields();
        if extra_count != 0 {
            write!(f, ", .. ({} fields)", extra_count)?;
        }
        write!(f, " }}")
    }
}
impl<'r> WithdrawalIntentDataReader<'r> {
    pub const FIELD_COUNT: usize = 5;
    pub fn total_size(&self) -> usize {
        molecule::unpack_number(self.as_slice()) as usize
    }
    pub fn field_count(&self) -> usize {
        if self.total_size() == molecule::NUMBER_SIZE {
            0
        } else {
            (molecule::unpack_number(&self.as_slice()[molecule::NUMBER_SIZE..]) as usize / 4) - 1
        }
    }
    pub fn count_extra_fields(&self) -> usize {
        self.field_count() - Self::FIELD_COUNT
    }
    pub fn has_extra_fields(&self) -> bool {
        Self::FIELD_COUNT != self.field_count()
    }
    pub fn xudt_script_hash(&self) -> Byte32Reader<'r> {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[4..]) as usize;
        let end = molecule::unpack_number(&slice[8..]) as usize;
        Byte32Reader::new_unchecked(&self.as_slice()[start..end])
    }
    pub fn xudt_lock_script_hash(&self) -> Byte32Reader<'r> {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[8..]) as usize;
        let end = molecule::unpack_number(&slice[12..]) as usize;
        Byte32Reader::new_unchecked(&self.as_slice()[start..end])
    }
    pub fn buyer(&self) -> WithdrawalBuyerReader<'r> {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[12..]) as usize;
        let end = molecule::unpack_number(&slice[16..]) as usize;
        WithdrawalBuyerReader::new_unchecked(&self.as_slice()[start..end])
    }
    pub fn expire_since(&self) -> Uint64Reader<'r> {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[16..]) as usize;
        let end = molecule::unpack_number(&slice[20..]) as usize;
        Uint64Reader::new_unchecked(&self.as_slice()[start..end])
    }
    pub fn owner_script_hash(&self) -> Byte32Reader<'r> {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[20..]) as usize;
        if self.has_extra_fields() {
            let end = molecule::unpack_number(&slice[24..]) as usize;
            Byte32Reader::new_unchecked(&self.as_slice()[start..end])
        } else {
            Byte32Reader::new_unchecked(&self.as_slice()[start..])
        }
    }
}
impl<'r> molecule::prelude::Reader<'r> for WithdrawalIntentDataReader<'r> {
    type Entity = WithdrawalIntentData;
    const NAME: &'static str = "WithdrawalIntentDataReader";
    fn to_entity(&self) -> Self::Entity {
        Self::Entity::new_unchecked(self.as_slice().to_owned().into())
    }
    fn new_unchecked(slice: &'r [u8]) -> Self {
        WithdrawalIntentDataReader(slice)
    }
    fn as_slice(&self) -> &'r [u8] {
        self.0
    }
    fn verify(slice: &[u8], compatible: bool) -> molecule::error::VerificationResult<()> {
        use molecule::verification_error as ve;
        let slice_len = slice.len();
        if slice_len < molecule::NUMBER_SIZE {
            return ve!(Self, HeaderIsBroken, molecule::NUMBER_SIZE, slice_len);
        }
        let total_size = molecule::unpack_number(slice) as usize;
        if slice_len != total_size {
            return ve!(Self, TotalSizeNotMatch, total_size, slice_len);
        }
        if slice_len < molecule::NUMBER_SIZE * 2 {
            return ve!(Self, HeaderIsBroken, molecule::NUMBER_SIZE * 2, slice_len);
        }
        let offset_first = molecule::unpack_number(&slice[molecule::NUMBER_SIZE..]) as usize;
        if offset_first % molecule::NUMBER_SIZE != 0 || offset_first < molecule::NUMBER_SIZE * 2 {
            return ve!(Self, OffsetsNotMatch);
        }
        if slice_len < offset_first {
            return ve!(Self, HeaderIsBroken, offset_first, slice_len);
        }
        let field_count = offset_first / molecule::NUMBER_SIZE - 1;
        if field_count < Self::FIELD_COUNT {
            return ve!(Self, FieldCountNotMatch, Self::FIELD_COUNT, field_count);
        } else if !compatible && field_count > Self::FIELD_COUNT {
            return ve!(Self, FieldCountNotMatch, Self::FIELD_COUNT, field_count);
        };
        let mut offsets: Vec<usize> = slice[molecule::NUMBER_SIZE..offset_first]
            .chunks_exact(molecule::NUMBER_SIZE)
            .map(|x| molecule::unpack_number(x) as usize)
            .collect();
        offsets.push(total_size);
        if offsets.windows(2).any(|i| i[0] > i[1]) {
            return ve!(Self, OffsetsNotMatch);
        }
        Byte32Reader::verify(&slice[offsets[0]..offsets[1]], compatible)?;
        Byte32Reader::verify(&slice[offsets[1]..offsets[2]], compatible)?;
        WithdrawalBuyerReader::verify(&slice[offsets[2]..offsets[3]], compatible)?;
        Uint64Reader::verify(&slice[offsets[3]..offsets[4]], compatible)?;
        Byte32Reader::verify(&slice[offsets[4]..offsets[5]], compatible)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default)]
pub struct WithdrawalIntentDataBuilder {
    pub(crate) xudt_script_hash: Byte32,
    pub(crate) xudt_lock_script_hash: Byte32,
    pub(crate) buyer: WithdrawalBuyer,
    pub(crate) expire_since: Uint64,
    pub(crate) owner_script_hash: Byte32,
}
impl WithdrawalIntentDataBuilder {
    pub const FIELD_COUNT: usize = 5;
    pub fn xudt_script_hash(mut self, v: Byte32) -> Self {
        self.xudt_script_hash = v;
        self
    }
    pub fn xudt_lock_script_hash(mut self, v: Byte32) -> Self {
        self.xudt_lock_script_hash = v;
        self
    }
    pub fn buyer(mut self, v: WithdrawalBuyer) -> Self {
        self.buyer = v;
        self
    }
    pub fn expire_since(mut self, v: Uint64) -> Self {
        self.expire_since = v;
        self
    }
    pub fn owner_script_hash(mut self, v: Byte32) -> Self {
        self.owner_script_hash = v;
        self
    }
}
impl molecule::prelude::Builder for WithdrawalIntentDataBuilder {
    type Entity = WithdrawalIntentData;
    const NAME: &'static str = "WithdrawalIntentDataBuilder";
    fn expected_length(&self) -> usize {
        molecule::NUMBER_SIZE * (Self::FIELD_COUNT + 1)
            + self.xudt_script_hash.as_slice().len()
            + self.xudt_lock_script_hash.as_slice().len()
            + self.buyer.as_slice().len()
            + self.expire_since.as_slice().len()
            + self.owner_script_hash.as_slice().len()
    }
    fn write<W: molecule::io::Write>(&self, writer: &mut W) -> molecule::io::Result<()> {
        let mut total_size = molecule::NUMBER_SIZE * (Self::FIELD_COUNT + 1);
        let mut offsets = Vec::with_capacity(Self::FIELD_COUNT);
        offsets.push(total_size);
        total_size += self.xudt_script_hash.as_slice().len();
        offsets.push(total_size);
        total_size += self.xudt_lock_script_hash.as_slice().len();
        offsets.push(total_size);
        total_size += self.buyer.as_slice().len();
        offsets.push(total_size);
        total_size += self.expire_since.as_slice().len();
        offsets.push(total_size);
        total_size += self.owner_script_hash.as_slice().len();
        writer.write_all(&molecule::pack_number(total_size as molecule::Number))?;
        for offset in offsets.into_iter() {
            writer.write_all(&molecule::pack_number(offset as molecule::Number))?;
        }
        writer.write_all(self.xudt_script_hash.as_slice())?;
        writer.write_all(self.xudt_lock_script_hash.as_slice())?;
        writer.write_all(self.buyer.as_slice())?;
        writer.write_all(self.expire_since.as_slice())?;
        writer.write_all(self.owner_script_hash.as_slice())?;
        Ok(())
    }
    fn build(&self) -> Self::Entity {
        let mut inner = Vec::with_capacity(self.expected_length());
        self.write(&mut inner)
            .unwrap_or_else(|_| panic!("{} build should be ok", Self::NAME));
        WithdrawalIntentData::new_unchecked(inner.into())
    }
}
#[derive(Clone)]
pub struct AccountBookData(molecule::bytes::Bytes);
impl ::core::fmt::LowerHex for AccountBookData {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        use molecule::hex_string;
        if f.alternate() {
            write!(f, "0x")?;
        }
        write!(f, "{}", hex_string(self.as_slice()))
    }
}
impl ::core::fmt::Debug for AccountBookData {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{}({:#x})", Self::NAME, self)
    }
}
impl ::core::fmt::Display for AccountBookData {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{} {{ ", Self::NAME)?;
        write!(f, "{}: {}", "proof", self.proof())?;
        write!(f, ", {}: {}", "total_income_udt", self.total_income_udt())?;
        write!(f, ", {}: {}", "withdrawn_udt", self.withdrawn_udt())?;
        let extra_count = self.count_extra_fields();
        if extra_count != 0 {
            write!(f, ", .. ({} fields)", extra_count)?;
        }
        write!(f, " }}")
    }
}
impl ::core::default::Default for AccountBookData {
    fn default() -> Self {
        let v = molecule::bytes::Bytes::from_static(&Self::DEFAULT_VALUE);
        AccountBookData::new_unchecked(v)
    }
}
impl AccountBookData {
    const DEFAULT_VALUE: [u8; 36] = [
        36, 0, 0, 0, 16, 0, 0, 0, 20, 0, 0, 0, 36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0,
    ];
    pub const FIELD_COUNT: usize = 3;
    pub fn total_size(&self) -> usize {
        molecule::unpack_number(self.as_slice()) as usize
    }
    pub fn field_count(&self) -> usize {
        if self.total_size() == molecule::NUMBER_SIZE {
            0
        } else {
            (molecule::unpack_number(&self.as_slice()[molecule::NUMBER_SIZE..]) as usize / 4) - 1
        }
    }
    pub fn count_extra_fields(&self) -> usize {
        self.field_count() - Self::FIELD_COUNT
    }
    pub fn has_extra_fields(&self) -> bool {
        Self::FIELD_COUNT != self.field_count()
    }
    pub fn proof(&self) -> Bytes {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[4..]) as usize;
        let end = molecule::unpack_number(&slice[8..]) as usize;
        Bytes::new_unchecked(self.0.slice(start..end))
    }
    pub fn total_income_udt(&self) -> Uint128 {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[8..]) as usize;
        let end = molecule::unpack_number(&slice[12..]) as usize;
        Uint128::new_unchecked(self.0.slice(start..end))
    }
    pub fn withdrawn_udt(&self) -> Uint128Opt {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[12..]) as usize;
        if self.has_extra_fields() {
            let end = molecule::unpack_number(&slice[16..]) as usize;
            Uint128Opt::new_unchecked(self.0.slice(start..end))
        } else {
            Uint128Opt::new_unchecked(self.0.slice(start..))
        }
    }
    pub fn as_reader<'r>(&'r self) -> AccountBookDataReader<'r> {
        AccountBookDataReader::new_unchecked(self.as_slice())
    }
}
impl molecule::prelude::Entity for AccountBookData {
    type Builder = AccountBookDataBuilder;
    const NAME: &'static str = "AccountBookData";
    fn new_unchecked(data: molecule::bytes::Bytes) -> Self {
        AccountBookData(data)
    }
    fn as_bytes(&self) -> molecule::bytes::Bytes {
        self.0.clone()
    }
    fn as_slice(&self) -> &[u8] {
        &self.0[..]
    }
    fn from_slice(slice: &[u8]) -> molecule::error::VerificationResult<Self> {
        AccountBookDataReader::from_slice(slice).map(|reader| reader.to_entity())
    }
    fn from_compatible_slice(slice: &[u8]) -> molecule::error::VerificationResult<Self> {
        AccountBookDataReader::from_compatible_slice(slice).map(|reader| reader.to_entity())
    }
    fn new_builder() -> Self::Builder {
        ::core::default::Default::default()
    }
    fn as_builder(self) -> Self::Builder {
        Self::new_builder()
            .proof(self.proof())
            .total_income_udt(self.total_income_udt())
            .withdrawn_udt(self.withdrawn_udt())
    }
}
#[derive(Clone, Copy)]
pub struct AccountBookDataReader<'r>(&'r [u8]);
impl<'r> ::core::fmt::LowerHex for AccountBookDataReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        use molecule::hex_string;
        if f.alternate() {
            write!(f, "0x")?;
        }
        write!(f, "{}", hex_string(self.as_slice()))
    }
}
impl<'r> ::core::fmt::Debug for AccountBookDataReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{}({:#x})", Self::NAME, self)
    }
}
impl<'r> ::core::fmt::Display for AccountBookDataReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{} {{ ", Self::NAME)?;
        write!(f, "{}: {}", "proof", self.proof())?;
        write!(f, ", {}: {}", "total_income_udt", self.total_income_udt())?;
        write!(f, ", {}: {}", "withdrawn_udt", self.withdrawn_udt())?;
        let extra_count = self.count_extra_fields();
        if extra_count != 0 {
            write!(f, ", .. ({} fields)", extra_count)?;
        }
        write!(f, " }}")
    }
}
impl<'r> AccountBookDataReader<'r> {
    pub const FIELD_COUNT: usize = 3;
    pub fn total_size(&self) -> usize {
        molecule::unpack_number(self.as_slice()) as usize
    }
    pub fn field_count(&self) -> usize {
        if self.total_size() == molecule::NUMBER_SIZE {
            0
        } else {
            (molecule::unpack_number(&self.as_slice()[molecule::NUMBER_SIZE..]) as usize / 4) - 1
        }
    }
    pub fn count_extra_fields(&self) -> usize {
        self.field_count() - Self::FIELD_COUNT
    }
    pub fn has_extra_fields(&self) -> bool {
        Self::FIELD_COUNT != self.field_count()
    }
    pub fn proof(&self) -> BytesReader<'r> {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[4..]) as usize;
        let end = molecule::unpack_number(&slice[8..]) as usize;
        BytesReader::new_unchecked(&self.as_slice()[start..end])
    }
    pub fn total_income_udt(&self) -> Uint128Reader<'r> {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[8..]) as usize;
        let end = molecule::unpack_number(&slice[12..]) as usize;
        Uint128Reader::new_unchecked(&self.as_slice()[start..end])
    }
    pub fn withdrawn_udt(&self) -> Uint128OptReader<'r> {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[12..]) as usize;
        if self.has_extra_fields() {
            let end = molecule::unpack_number(&slice[16..]) as usize;
            Uint128OptReader::new_unchecked(&self.as_slice()[start..end])
        } else {
            Uint128OptReader::new_unchecked(&self.as_slice()[start..])
        }
    }
}
impl<'r> molecule::prelude::Reader<'r> for AccountBookDataReader<'r> {
    type Entity = AccountBookData;
    const NAME: &'static str = "AccountBookDataReader";
    fn to_entity(&self) -> Self::Entity {
        Self::Entity::new_unchecked(self.as_slice().to_owned().into())
    }
    fn new_unchecked(slice: &'r [u8]) -> Self {
        AccountBookDataReader(slice)
    }
    fn as_slice(&self) -> &'r [u8] {
        self.0
    }
    fn verify(slice: &[u8], compatible: bool) -> molecule::error::VerificationResult<()> {
        use molecule::verification_error as ve;
        let slice_len = slice.len();
        if slice_len < molecule::NUMBER_SIZE {
            return ve!(Self, HeaderIsBroken, molecule::NUMBER_SIZE, slice_len);
        }
        let total_size = molecule::unpack_number(slice) as usize;
        if slice_len != total_size {
            return ve!(Self, TotalSizeNotMatch, total_size, slice_len);
        }
        if slice_len < molecule::NUMBER_SIZE * 2 {
            return ve!(Self, HeaderIsBroken, molecule::NUMBER_SIZE * 2, slice_len);
        }
        let offset_first = molecule::unpack_number(&slice[molecule::NUMBER_SIZE..]) as usize;
        if offset_first % molecule::NUMBER_SIZE != 0 || offset_first < molecule::NUMBER_SIZE * 2 {
            return ve!(Self, OffsetsNotMatch);
        }
        if slice_len < offset_first {
            return ve!(Self, HeaderIsBroken, offset_first, slice_len);
        }
        let field_count = offset_first / molecule::NUMBER_SIZE - 1;
        if field_count < Self::FIELD_COUNT {
            return ve!(Self, FieldCountNotMatch, Self::FIELD_COUNT, field_count);
        } else if !compatible && field_count > Self::FIELD_COUNT {
            return ve!(Self, FieldCountNotMatch, Self::FIELD_COUNT, field_count);
        };
        let mut offsets: Vec<usize> = slice[molecule::NUMBER_SIZE..offset_first]
            .chunks_exact(molecule::NUMBER_SIZE)
            .map(|x| molecule::unpack_number(x) as usize)
            .collect();
        offsets.push(total_size);
        if offsets.windows(2).any(|i| i[0] > i[1]) {
            return ve!(Self, OffsetsNotMatch);
        }
        BytesReader::verify(&slice[offsets[0]..offsets[1]], compatible)?;
        Uint128Reader::verify(&slice[offsets[1]..offsets[2]], compatible)?;
        Uint128OptReader::verify(&slice[offsets[2]..offsets[3]], compatible)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default)]
pub struct AccountBookDataBuilder {
    pub(crate) proof: Bytes,
    pub(crate) total_income_udt: Uint128,
    pub(crate) withdrawn_udt: Uint128Opt,
}
impl AccountBookDataBuilder {
    pub const FIELD_COUNT: usize = 3;
    pub fn proof(mut self, v: Bytes) -> Self {
        self.proof = v;
        self
    }
    pub fn total_income_udt(mut self, v: Uint128) -> Self {
        self.total_income_udt = v;
        self
    }
    pub fn withdrawn_udt(mut self, v: Uint128Opt) -> Self {
        self.withdrawn_udt = v;
        self
    }
}
impl molecule::prelude::Builder for AccountBookDataBuilder {
    type Entity = AccountBookData;
    const NAME: &'static str = "AccountBookDataBuilder";
    fn expected_length(&self) -> usize {
        molecule::NUMBER_SIZE * (Self::FIELD_COUNT + 1)
            + self.proof.as_slice().len()
            + self.total_income_udt.as_slice().len()
            + self.withdrawn_udt.as_slice().len()
    }
    fn write<W: molecule::io::Write>(&self, writer: &mut W) -> molecule::io::Result<()> {
        let mut total_size = molecule::NUMBER_SIZE * (Self::FIELD_COUNT + 1);
        let mut offsets = Vec::with_capacity(Self::FIELD_COUNT);
        offsets.push(total_size);
        total_size += self.proof.as_slice().len();
        offsets.push(total_size);
        total_size += self.total_income_udt.as_slice().len();
        offsets.push(total_size);
        total_size += self.withdrawn_udt.as_slice().len();
        writer.write_all(&molecule::pack_number(total_size as molecule::Number))?;
        for offset in offsets.into_iter() {
            writer.write_all(&molecule::pack_number(offset as molecule::Number))?;
        }
        writer.write_all(self.proof.as_slice())?;
        writer.write_all(self.total_income_udt.as_slice())?;
        writer.write_all(self.withdrawn_udt.as_slice())?;
        Ok(())
    }
    fn build(&self) -> Self::Entity {
        let mut inner = Vec::with_capacity(self.expected_length());
        self.write(&mut inner)
            .unwrap_or_else(|_| panic!("{} build should be ok", Self::NAME));
        AccountBookData::new_unchecked(inner.into())
    }
}
#[derive(Clone)]
pub struct AccountBookCellData(molecule::bytes::Bytes);
impl ::core::fmt::LowerHex for AccountBookCellData {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        use molecule::hex_string;
        if f.alternate() {
            write!(f, "0x")?;
        }
        write!(f, "{}", hex_string(self.as_slice()))
    }
}
impl ::core::fmt::Debug for AccountBookCellData {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{}({:#x})", Self::NAME, self)
    }
}
impl ::core::fmt::Display for AccountBookCellData {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{} {{ ", Self::NAME)?;
        write!(f, "{}: {}", "smt_root_hash", self.smt_root_hash())?;
        write!(f, ", {}: {}", "buyer_count", self.buyer_count())?;
        write!(
            f,
            ", {}: {}",
            "dob_selling_code_hash",
            self.dob_selling_code_hash()
        )?;
        write!(
            f,
            ", {}: {}",
            "buy_intent_code_hash",
            self.buy_intent_code_hash()
        )?;
        write!(
            f,
            ", {}: {}",
            "withdrawal_intent_code_hash",
            self.withdrawal_intent_code_hash()
        )?;
        write!(f, ", {}: {}", "xudt_script_hash", self.xudt_script_hash())?;
        write!(
            f,
            ", {}: {}",
            "input_type_proxy_lock_code_hash",
            self.input_type_proxy_lock_code_hash()
        )?;
        write!(f, ", {}: {}", "cluster_id", self.cluster_id())?;
        write!(f, ", {}: {}", "level", self.level())?;
        write!(f, ", {}: {}", "auther_id", self.auther_id())?;
        write!(f, ", {}: {}", "platform_id", self.platform_id())?;
        write!(f, ", {}: {}", "price", self.price())?;
        write!(
            f,
            ", {}: {}",
            "profit_distribution_ratio",
            self.profit_distribution_ratio()
        )?;
        write!(
            f,
            ", {}: {}",
            "profit_distribution_number",
            self.profit_distribution_number()
        )?;
        let extra_count = self.count_extra_fields();
        if extra_count != 0 {
            write!(f, ", .. ({} fields)", extra_count)?;
        }
        write!(f, " }}")
    }
}
impl ::core::default::Default for AccountBookCellData {
    fn default() -> Self {
        let v = molecule::bytes::Bytes::from_static(&Self::DEFAULT_VALUE);
        AccountBookCellData::new_unchecked(v)
    }
}
impl AccountBookCellData {
    const DEFAULT_VALUE: [u8; 377] = [
        121, 1, 0, 0, 60, 0, 0, 0, 92, 0, 0, 0, 96, 0, 0, 0, 128, 0, 0, 0, 160, 0, 0, 0, 192, 0, 0,
        0, 224, 0, 0, 0, 0, 1, 0, 0, 32, 1, 0, 0, 33, 1, 0, 0, 65, 1, 0, 0, 97, 1, 0, 0, 113, 1, 0,
        0, 117, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    ];
    pub const FIELD_COUNT: usize = 14;
    pub fn total_size(&self) -> usize {
        molecule::unpack_number(self.as_slice()) as usize
    }
    pub fn field_count(&self) -> usize {
        if self.total_size() == molecule::NUMBER_SIZE {
            0
        } else {
            (molecule::unpack_number(&self.as_slice()[molecule::NUMBER_SIZE..]) as usize / 4) - 1
        }
    }
    pub fn count_extra_fields(&self) -> usize {
        self.field_count() - Self::FIELD_COUNT
    }
    pub fn has_extra_fields(&self) -> bool {
        Self::FIELD_COUNT != self.field_count()
    }
    pub fn smt_root_hash(&self) -> Byte32 {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[4..]) as usize;
        let end = molecule::unpack_number(&slice[8..]) as usize;
        Byte32::new_unchecked(self.0.slice(start..end))
    }
    pub fn buyer_count(&self) -> Uint32 {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[8..]) as usize;
        let end = molecule::unpack_number(&slice[12..]) as usize;
        Uint32::new_unchecked(self.0.slice(start..end))
    }
    pub fn dob_selling_code_hash(&self) -> Byte32 {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[12..]) as usize;
        let end = molecule::unpack_number(&slice[16..]) as usize;
        Byte32::new_unchecked(self.0.slice(start..end))
    }
    pub fn buy_intent_code_hash(&self) -> Byte32 {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[16..]) as usize;
        let end = molecule::unpack_number(&slice[20..]) as usize;
        Byte32::new_unchecked(self.0.slice(start..end))
    }
    pub fn withdrawal_intent_code_hash(&self) -> Byte32 {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[20..]) as usize;
        let end = molecule::unpack_number(&slice[24..]) as usize;
        Byte32::new_unchecked(self.0.slice(start..end))
    }
    pub fn xudt_script_hash(&self) -> Byte32 {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[24..]) as usize;
        let end = molecule::unpack_number(&slice[28..]) as usize;
        Byte32::new_unchecked(self.0.slice(start..end))
    }
    pub fn input_type_proxy_lock_code_hash(&self) -> Byte32 {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[28..]) as usize;
        let end = molecule::unpack_number(&slice[32..]) as usize;
        Byte32::new_unchecked(self.0.slice(start..end))
    }
    pub fn cluster_id(&self) -> Byte32 {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[32..]) as usize;
        let end = molecule::unpack_number(&slice[36..]) as usize;
        Byte32::new_unchecked(self.0.slice(start..end))
    }
    pub fn level(&self) -> Byte {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[36..]) as usize;
        let end = molecule::unpack_number(&slice[40..]) as usize;
        Byte::new_unchecked(self.0.slice(start..end))
    }
    pub fn auther_id(&self) -> Byte32 {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[40..]) as usize;
        let end = molecule::unpack_number(&slice[44..]) as usize;
        Byte32::new_unchecked(self.0.slice(start..end))
    }
    pub fn platform_id(&self) -> Byte32 {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[44..]) as usize;
        let end = molecule::unpack_number(&slice[48..]) as usize;
        Byte32::new_unchecked(self.0.slice(start..end))
    }
    pub fn price(&self) -> Uint128 {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[48..]) as usize;
        let end = molecule::unpack_number(&slice[52..]) as usize;
        Uint128::new_unchecked(self.0.slice(start..end))
    }
    pub fn profit_distribution_ratio(&self) -> Bytes {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[52..]) as usize;
        let end = molecule::unpack_number(&slice[56..]) as usize;
        Bytes::new_unchecked(self.0.slice(start..end))
    }
    pub fn profit_distribution_number(&self) -> Bytes {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[56..]) as usize;
        if self.has_extra_fields() {
            let end = molecule::unpack_number(&slice[60..]) as usize;
            Bytes::new_unchecked(self.0.slice(start..end))
        } else {
            Bytes::new_unchecked(self.0.slice(start..))
        }
    }
    pub fn as_reader<'r>(&'r self) -> AccountBookCellDataReader<'r> {
        AccountBookCellDataReader::new_unchecked(self.as_slice())
    }
}
impl molecule::prelude::Entity for AccountBookCellData {
    type Builder = AccountBookCellDataBuilder;
    const NAME: &'static str = "AccountBookCellData";
    fn new_unchecked(data: molecule::bytes::Bytes) -> Self {
        AccountBookCellData(data)
    }
    fn as_bytes(&self) -> molecule::bytes::Bytes {
        self.0.clone()
    }
    fn as_slice(&self) -> &[u8] {
        &self.0[..]
    }
    fn from_slice(slice: &[u8]) -> molecule::error::VerificationResult<Self> {
        AccountBookCellDataReader::from_slice(slice).map(|reader| reader.to_entity())
    }
    fn from_compatible_slice(slice: &[u8]) -> molecule::error::VerificationResult<Self> {
        AccountBookCellDataReader::from_compatible_slice(slice).map(|reader| reader.to_entity())
    }
    fn new_builder() -> Self::Builder {
        ::core::default::Default::default()
    }
    fn as_builder(self) -> Self::Builder {
        Self::new_builder()
            .smt_root_hash(self.smt_root_hash())
            .buyer_count(self.buyer_count())
            .dob_selling_code_hash(self.dob_selling_code_hash())
            .buy_intent_code_hash(self.buy_intent_code_hash())
            .withdrawal_intent_code_hash(self.withdrawal_intent_code_hash())
            .xudt_script_hash(self.xudt_script_hash())
            .input_type_proxy_lock_code_hash(self.input_type_proxy_lock_code_hash())
            .cluster_id(self.cluster_id())
            .level(self.level())
            .auther_id(self.auther_id())
            .platform_id(self.platform_id())
            .price(self.price())
            .profit_distribution_ratio(self.profit_distribution_ratio())
            .profit_distribution_number(self.profit_distribution_number())
    }
}
#[derive(Clone, Copy)]
pub struct AccountBookCellDataReader<'r>(&'r [u8]);
impl<'r> ::core::fmt::LowerHex for AccountBookCellDataReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        use molecule::hex_string;
        if f.alternate() {
            write!(f, "0x")?;
        }
        write!(f, "{}", hex_string(self.as_slice()))
    }
}
impl<'r> ::core::fmt::Debug for AccountBookCellDataReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{}({:#x})", Self::NAME, self)
    }
}
impl<'r> ::core::fmt::Display for AccountBookCellDataReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{} {{ ", Self::NAME)?;
        write!(f, "{}: {}", "smt_root_hash", self.smt_root_hash())?;
        write!(f, ", {}: {}", "buyer_count", self.buyer_count())?;
        write!(
            f,
            ", {}: {}",
            "dob_selling_code_hash",
            self.dob_selling_code_hash()
        )?;
        write!(
            f,
            ", {}: {}",
            "buy_intent_code_hash",
            self.buy_intent_code_hash()
        )?;
        write!(
            f,
            ", {}: {}",
            "withdrawal_intent_code_hash",
            self.withdrawal_intent_code_hash()
        )?;
        write!(f, ", {}: {}", "xudt_script_hash", self.xudt_script_hash())?;
        write!(
            f,
            ", {}: {}",
            "input_type_proxy_lock_code_hash",
            self.input_type_proxy_lock_code_hash()
        )?;
        write!(f, ", {}: {}", "cluster_id", self.cluster_id())?;
        write!(f, ", {}: {}", "level", self.level())?;
        write!(f, ", {}: {}", "auther_id", self.auther_id())?;
        write!(f, ", {}: {}", "platform_id", self.platform_id())?;
        write!(f, ", {}: {}", "price", self.price())?;
        write!(
            f,
            ", {}: {}",
            "profit_distribution_ratio",
            self.profit_distribution_ratio()
        )?;
        write!(
            f,
            ", {}: {}",
            "profit_distribution_number",
            self.profit_distribution_number()
        )?;
        let extra_count = self.count_extra_fields();
        if extra_count != 0 {
            write!(f, ", .. ({} fields)", extra_count)?;
        }
        write!(f, " }}")
    }
}
impl<'r> AccountBookCellDataReader<'r> {
    pub const FIELD_COUNT: usize = 14;
    pub fn total_size(&self) -> usize {
        molecule::unpack_number(self.as_slice()) as usize
    }
    pub fn field_count(&self) -> usize {
        if self.total_size() == molecule::NUMBER_SIZE {
            0
        } else {
            (molecule::unpack_number(&self.as_slice()[molecule::NUMBER_SIZE..]) as usize / 4) - 1
        }
    }
    pub fn count_extra_fields(&self) -> usize {
        self.field_count() - Self::FIELD_COUNT
    }
    pub fn has_extra_fields(&self) -> bool {
        Self::FIELD_COUNT != self.field_count()
    }
    pub fn smt_root_hash(&self) -> Byte32Reader<'r> {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[4..]) as usize;
        let end = molecule::unpack_number(&slice[8..]) as usize;
        Byte32Reader::new_unchecked(&self.as_slice()[start..end])
    }
    pub fn buyer_count(&self) -> Uint32Reader<'r> {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[8..]) as usize;
        let end = molecule::unpack_number(&slice[12..]) as usize;
        Uint32Reader::new_unchecked(&self.as_slice()[start..end])
    }
    pub fn dob_selling_code_hash(&self) -> Byte32Reader<'r> {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[12..]) as usize;
        let end = molecule::unpack_number(&slice[16..]) as usize;
        Byte32Reader::new_unchecked(&self.as_slice()[start..end])
    }
    pub fn buy_intent_code_hash(&self) -> Byte32Reader<'r> {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[16..]) as usize;
        let end = molecule::unpack_number(&slice[20..]) as usize;
        Byte32Reader::new_unchecked(&self.as_slice()[start..end])
    }
    pub fn withdrawal_intent_code_hash(&self) -> Byte32Reader<'r> {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[20..]) as usize;
        let end = molecule::unpack_number(&slice[24..]) as usize;
        Byte32Reader::new_unchecked(&self.as_slice()[start..end])
    }
    pub fn xudt_script_hash(&self) -> Byte32Reader<'r> {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[24..]) as usize;
        let end = molecule::unpack_number(&slice[28..]) as usize;
        Byte32Reader::new_unchecked(&self.as_slice()[start..end])
    }
    pub fn input_type_proxy_lock_code_hash(&self) -> Byte32Reader<'r> {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[28..]) as usize;
        let end = molecule::unpack_number(&slice[32..]) as usize;
        Byte32Reader::new_unchecked(&self.as_slice()[start..end])
    }
    pub fn cluster_id(&self) -> Byte32Reader<'r> {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[32..]) as usize;
        let end = molecule::unpack_number(&slice[36..]) as usize;
        Byte32Reader::new_unchecked(&self.as_slice()[start..end])
    }
    pub fn level(&self) -> ByteReader<'r> {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[36..]) as usize;
        let end = molecule::unpack_number(&slice[40..]) as usize;
        ByteReader::new_unchecked(&self.as_slice()[start..end])
    }
    pub fn auther_id(&self) -> Byte32Reader<'r> {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[40..]) as usize;
        let end = molecule::unpack_number(&slice[44..]) as usize;
        Byte32Reader::new_unchecked(&self.as_slice()[start..end])
    }
    pub fn platform_id(&self) -> Byte32Reader<'r> {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[44..]) as usize;
        let end = molecule::unpack_number(&slice[48..]) as usize;
        Byte32Reader::new_unchecked(&self.as_slice()[start..end])
    }
    pub fn price(&self) -> Uint128Reader<'r> {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[48..]) as usize;
        let end = molecule::unpack_number(&slice[52..]) as usize;
        Uint128Reader::new_unchecked(&self.as_slice()[start..end])
    }
    pub fn profit_distribution_ratio(&self) -> BytesReader<'r> {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[52..]) as usize;
        let end = molecule::unpack_number(&slice[56..]) as usize;
        BytesReader::new_unchecked(&self.as_slice()[start..end])
    }
    pub fn profit_distribution_number(&self) -> BytesReader<'r> {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[56..]) as usize;
        if self.has_extra_fields() {
            let end = molecule::unpack_number(&slice[60..]) as usize;
            BytesReader::new_unchecked(&self.as_slice()[start..end])
        } else {
            BytesReader::new_unchecked(&self.as_slice()[start..])
        }
    }
}
impl<'r> molecule::prelude::Reader<'r> for AccountBookCellDataReader<'r> {
    type Entity = AccountBookCellData;
    const NAME: &'static str = "AccountBookCellDataReader";
    fn to_entity(&self) -> Self::Entity {
        Self::Entity::new_unchecked(self.as_slice().to_owned().into())
    }
    fn new_unchecked(slice: &'r [u8]) -> Self {
        AccountBookCellDataReader(slice)
    }
    fn as_slice(&self) -> &'r [u8] {
        self.0
    }
    fn verify(slice: &[u8], compatible: bool) -> molecule::error::VerificationResult<()> {
        use molecule::verification_error as ve;
        let slice_len = slice.len();
        if slice_len < molecule::NUMBER_SIZE {
            return ve!(Self, HeaderIsBroken, molecule::NUMBER_SIZE, slice_len);
        }
        let total_size = molecule::unpack_number(slice) as usize;
        if slice_len != total_size {
            return ve!(Self, TotalSizeNotMatch, total_size, slice_len);
        }
        if slice_len < molecule::NUMBER_SIZE * 2 {
            return ve!(Self, HeaderIsBroken, molecule::NUMBER_SIZE * 2, slice_len);
        }
        let offset_first = molecule::unpack_number(&slice[molecule::NUMBER_SIZE..]) as usize;
        if offset_first % molecule::NUMBER_SIZE != 0 || offset_first < molecule::NUMBER_SIZE * 2 {
            return ve!(Self, OffsetsNotMatch);
        }
        if slice_len < offset_first {
            return ve!(Self, HeaderIsBroken, offset_first, slice_len);
        }
        let field_count = offset_first / molecule::NUMBER_SIZE - 1;
        if field_count < Self::FIELD_COUNT {
            return ve!(Self, FieldCountNotMatch, Self::FIELD_COUNT, field_count);
        } else if !compatible && field_count > Self::FIELD_COUNT {
            return ve!(Self, FieldCountNotMatch, Self::FIELD_COUNT, field_count);
        };
        let mut offsets: Vec<usize> = slice[molecule::NUMBER_SIZE..offset_first]
            .chunks_exact(molecule::NUMBER_SIZE)
            .map(|x| molecule::unpack_number(x) as usize)
            .collect();
        offsets.push(total_size);
        if offsets.windows(2).any(|i| i[0] > i[1]) {
            return ve!(Self, OffsetsNotMatch);
        }
        Byte32Reader::verify(&slice[offsets[0]..offsets[1]], compatible)?;
        Uint32Reader::verify(&slice[offsets[1]..offsets[2]], compatible)?;
        Byte32Reader::verify(&slice[offsets[2]..offsets[3]], compatible)?;
        Byte32Reader::verify(&slice[offsets[3]..offsets[4]], compatible)?;
        Byte32Reader::verify(&slice[offsets[4]..offsets[5]], compatible)?;
        Byte32Reader::verify(&slice[offsets[5]..offsets[6]], compatible)?;
        Byte32Reader::verify(&slice[offsets[6]..offsets[7]], compatible)?;
        Byte32Reader::verify(&slice[offsets[7]..offsets[8]], compatible)?;
        ByteReader::verify(&slice[offsets[8]..offsets[9]], compatible)?;
        Byte32Reader::verify(&slice[offsets[9]..offsets[10]], compatible)?;
        Byte32Reader::verify(&slice[offsets[10]..offsets[11]], compatible)?;
        Uint128Reader::verify(&slice[offsets[11]..offsets[12]], compatible)?;
        BytesReader::verify(&slice[offsets[12]..offsets[13]], compatible)?;
        BytesReader::verify(&slice[offsets[13]..offsets[14]], compatible)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default)]
pub struct AccountBookCellDataBuilder {
    pub(crate) smt_root_hash: Byte32,
    pub(crate) buyer_count: Uint32,
    pub(crate) dob_selling_code_hash: Byte32,
    pub(crate) buy_intent_code_hash: Byte32,
    pub(crate) withdrawal_intent_code_hash: Byte32,
    pub(crate) xudt_script_hash: Byte32,
    pub(crate) input_type_proxy_lock_code_hash: Byte32,
    pub(crate) cluster_id: Byte32,
    pub(crate) level: Byte,
    pub(crate) auther_id: Byte32,
    pub(crate) platform_id: Byte32,
    pub(crate) price: Uint128,
    pub(crate) profit_distribution_ratio: Bytes,
    pub(crate) profit_distribution_number: Bytes,
}
impl AccountBookCellDataBuilder {
    pub const FIELD_COUNT: usize = 14;
    pub fn smt_root_hash(mut self, v: Byte32) -> Self {
        self.smt_root_hash = v;
        self
    }
    pub fn buyer_count(mut self, v: Uint32) -> Self {
        self.buyer_count = v;
        self
    }
    pub fn dob_selling_code_hash(mut self, v: Byte32) -> Self {
        self.dob_selling_code_hash = v;
        self
    }
    pub fn buy_intent_code_hash(mut self, v: Byte32) -> Self {
        self.buy_intent_code_hash = v;
        self
    }
    pub fn withdrawal_intent_code_hash(mut self, v: Byte32) -> Self {
        self.withdrawal_intent_code_hash = v;
        self
    }
    pub fn xudt_script_hash(mut self, v: Byte32) -> Self {
        self.xudt_script_hash = v;
        self
    }
    pub fn input_type_proxy_lock_code_hash(mut self, v: Byte32) -> Self {
        self.input_type_proxy_lock_code_hash = v;
        self
    }
    pub fn cluster_id(mut self, v: Byte32) -> Self {
        self.cluster_id = v;
        self
    }
    pub fn level(mut self, v: Byte) -> Self {
        self.level = v;
        self
    }
    pub fn auther_id(mut self, v: Byte32) -> Self {
        self.auther_id = v;
        self
    }
    pub fn platform_id(mut self, v: Byte32) -> Self {
        self.platform_id = v;
        self
    }
    pub fn price(mut self, v: Uint128) -> Self {
        self.price = v;
        self
    }
    pub fn profit_distribution_ratio(mut self, v: Bytes) -> Self {
        self.profit_distribution_ratio = v;
        self
    }
    pub fn profit_distribution_number(mut self, v: Bytes) -> Self {
        self.profit_distribution_number = v;
        self
    }
}
impl molecule::prelude::Builder for AccountBookCellDataBuilder {
    type Entity = AccountBookCellData;
    const NAME: &'static str = "AccountBookCellDataBuilder";
    fn expected_length(&self) -> usize {
        molecule::NUMBER_SIZE * (Self::FIELD_COUNT + 1)
            + self.smt_root_hash.as_slice().len()
            + self.buyer_count.as_slice().len()
            + self.dob_selling_code_hash.as_slice().len()
            + self.buy_intent_code_hash.as_slice().len()
            + self.withdrawal_intent_code_hash.as_slice().len()
            + self.xudt_script_hash.as_slice().len()
            + self.input_type_proxy_lock_code_hash.as_slice().len()
            + self.cluster_id.as_slice().len()
            + self.level.as_slice().len()
            + self.auther_id.as_slice().len()
            + self.platform_id.as_slice().len()
            + self.price.as_slice().len()
            + self.profit_distribution_ratio.as_slice().len()
            + self.profit_distribution_number.as_slice().len()
    }
    fn write<W: molecule::io::Write>(&self, writer: &mut W) -> molecule::io::Result<()> {
        let mut total_size = molecule::NUMBER_SIZE * (Self::FIELD_COUNT + 1);
        let mut offsets = Vec::with_capacity(Self::FIELD_COUNT);
        offsets.push(total_size);
        total_size += self.smt_root_hash.as_slice().len();
        offsets.push(total_size);
        total_size += self.buyer_count.as_slice().len();
        offsets.push(total_size);
        total_size += self.dob_selling_code_hash.as_slice().len();
        offsets.push(total_size);
        total_size += self.buy_intent_code_hash.as_slice().len();
        offsets.push(total_size);
        total_size += self.withdrawal_intent_code_hash.as_slice().len();
        offsets.push(total_size);
        total_size += self.xudt_script_hash.as_slice().len();
        offsets.push(total_size);
        total_size += self.input_type_proxy_lock_code_hash.as_slice().len();
        offsets.push(total_size);
        total_size += self.cluster_id.as_slice().len();
        offsets.push(total_size);
        total_size += self.level.as_slice().len();
        offsets.push(total_size);
        total_size += self.auther_id.as_slice().len();
        offsets.push(total_size);
        total_size += self.platform_id.as_slice().len();
        offsets.push(total_size);
        total_size += self.price.as_slice().len();
        offsets.push(total_size);
        total_size += self.profit_distribution_ratio.as_slice().len();
        offsets.push(total_size);
        total_size += self.profit_distribution_number.as_slice().len();
        writer.write_all(&molecule::pack_number(total_size as molecule::Number))?;
        for offset in offsets.into_iter() {
            writer.write_all(&molecule::pack_number(offset as molecule::Number))?;
        }
        writer.write_all(self.smt_root_hash.as_slice())?;
        writer.write_all(self.buyer_count.as_slice())?;
        writer.write_all(self.dob_selling_code_hash.as_slice())?;
        writer.write_all(self.buy_intent_code_hash.as_slice())?;
        writer.write_all(self.withdrawal_intent_code_hash.as_slice())?;
        writer.write_all(self.xudt_script_hash.as_slice())?;
        writer.write_all(self.input_type_proxy_lock_code_hash.as_slice())?;
        writer.write_all(self.cluster_id.as_slice())?;
        writer.write_all(self.level.as_slice())?;
        writer.write_all(self.auther_id.as_slice())?;
        writer.write_all(self.platform_id.as_slice())?;
        writer.write_all(self.price.as_slice())?;
        writer.write_all(self.profit_distribution_ratio.as_slice())?;
        writer.write_all(self.profit_distribution_number.as_slice())?;
        Ok(())
    }
    fn build(&self) -> Self::Entity {
        let mut inner = Vec::with_capacity(self.expected_length());
        self.write(&mut inner)
            .unwrap_or_else(|_| panic!("{} build should be ok", Self::NAME));
        AccountBookCellData::new_unchecked(inner.into())
    }
}
