name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Install llvm
      run: sudo apt update && sudo apt install -y clang
    - name: Instell rust risc-v
      run: rustup target add riscv64imac-unknown-none-elf
    - name: Install JS Deps
      run: cd ts && pnpm install
    - name: Build all
      run: make build build-js
    - name: Run Test
      run: make test check fmt clippy
    - name: Run JS Test
      run: make test-js
